# config.yaml

# complex-query test program

default:
  cluster:
    workers:    2
  mongodb:
    url:        mongodb://localhost/books
  logger:
    level:      info
    path:       ./complex-query.log
  server:
    hostname:   '127.0.0.1'
    port:       8086
development:
production:
